# Generated by Django 6.0.5 on 2026-05-09 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX IF EXISTS rutinas_rutina_usuario_id_be9f0492;",
            "CREATE INDEX rutinas_rutina_usuario_id_be9f0492 ON rutinas_rutina (usuario_id);",
        ),
        migrations.RunSQL(
            "ALTER TABLE rutinas_rutina DROP COLUMN usuario_id;",
            "ALTER TABLE rutinas_rutina ADD COLUMN usuario_id bigint;",
        ),
        migrations.AddField(
            model_name='rutina',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
