# Generated by Django 6.0.5 on 2026-05-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('descanso', models.IntegerField()),
                ('intensidad', models.IntegerField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejercicios.ejercicio')),
            ],
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(to='rutinas.listaejercicios'),
        ),
    ]
