# Generated by Django 6.0.5 on 2026-05-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_listaejercicios_alter_rutina_ejercicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='ejercicios',
        ),
    ]
