# Generated by Django 6.0.5 on 2026-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_remove_rutina_ejercicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='ListaEjercicios',
            field=models.ManyToManyField(to='rutinas.listaejercicios'),
        ),
    ]
