# Generated by Django 6.0.5 on 2026-05-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_usuario',
            new_name='Usuario',
        ),
    ]
